CREATE TABLE [User] (
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	Password NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_User PRIMARY KEY (ID asc)
);

CREATE TABLE IssueType (
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_IssueType PRIMARY KEY (ID asc)
);

CREATE TABLE Issue(
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Title NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	AssignedToUserID UNIQUEIDENTIFIER NULL,
	CurrentStageID UNIQUEIDENTIFIER NULL,
	IssueTypeID UNIQUEIDENTIFIER NOT NULL,
	ProjectID UNIQUEIDENTIFIER NULL,
	CreationDate DATETIME NULL,
	FinishDate DATETIME NULL,
	CONSTRAINT PK_Issue PRIMARY KEY (ID asc)
);

CREATE TABLE Comment(
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	IssueID UNIQUEIDENTIFIER NOT NULL,
	UserID UNIQUEIDENTIFIER NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_Comment PRIMARY KEY (ID asc)
);

CREATE TABLE Stage (
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_Stage PRIMARY KEY (ID asc)
);

CREATE TABLE Project (
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Name NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	MainUserID UNIQUEIDENTIFIER NULL,
	CONSTRAINT PK_Project PRIMARY KEY (ID asc)
);

ALTER TABLE Issue
ADD CONSTRAINT FK_Issue_User
FOREIGN KEY (AssignedToUserID) REFERENCES [User](ID);

ALTER TABLE Issue
ADD CONSTRAINT FK_Issue_IssueType
FOREIGN KEY (IssueTypeID) REFERENCES IssueType(ID);

ALTER TABLE Issue
ADD CONSTRAINT FK_Issue_Stage
FOREIGN KEY (CurrentStageID) REFERENCES Stage(ID);

ALTER TABLE Issue
ADD CONSTRAINT FK_Issue_Project
FOREIGN KEY (ProjectID) REFERENCES Project(ID);

ALTER TABLE Comment
ADD CONSTRAINT FK_Comment_Issue
FOREIGN KEY (IssueID) REFERENCES Issue(ID);

ALTER TABLE Comment
ADD CONSTRAINT FK_Comment_User
FOREIGN KEY (UserID) REFERENCES [User](ID);

ALTER TABLE Project
ADD CONSTRAINT FK_Project_User
FOREIGN KEY (MainUserID) REFERENCES [User](ID);